# Bank Churn Exercise - Building ANN

* Bank has been facing churn issue, measured the results 6 months ago
* Did the person leave or stay?
* Goal: ANN model, to predict which customers are highly likely to leave versus staying

In [107]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [108]:
# Check TF version:
tf.__version__

'2.17.0'

In [109]:
# Import dataset
dataset = pd.read_csv('Churn_Modelling.csv')

In [110]:
# Let's look at the dataset:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:, -1].values

In [111]:
# Notes:
# Import everything, include TF package
# The Customer ID is the key identifier, has no impact on dependent variable

# Does Surname have impact on Churn? Likely no

# Everything else will be kept, we will remove the first 2 

In [112]:
print(y)

[1 0 1 ... 1 1 0]


In [113]:
# Is there any missing data?
dataset.info()

# No missing data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [114]:
# Will need to encode some variables
from sklearn.preprocessing import LabelEncoder

In [115]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [116]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [117]:
# Call Encoder
le = LabelEncoder()

# We want to encode
# This is the 2nd column from the new truncated dataset

# Label Encoder will fail if you don't pass values into it, not the whole DF.
X[:,2] = le.fit_transform(X[:,2])

In [118]:
df = dataset.iloc[:,3:-1].copy()

In [119]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [120]:
# One Hot Encoding and transformers:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [121]:
# One Hot encode - geography columns:
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [1])], remainder = "passthrough")
# 1 = Geography is in column position 1 (counting from zero)

# passthrough means to apply transformation but do not drop the original columns
# Use this method instead of pandas - pd.encode()

In [122]:
# Apply the ct, column transformer we just made:
X = np.array(ct.fit_transform(X))

In [123]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [124]:
# Split X-train and X-test:
from sklearn.model_selection import train_test_split

# 20% testing, 42 random state
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [125]:
# Feature Scaling is mandatory, as deep learning is sensitive to larger ranges and outliers.
# Similar to Normal distribution
from sklearn.preprocessing import StandardScaler

In [126]:
# Apply the scale:
sc = StandardScaler()

# Fit and Transform
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Build the Artificial Neural Network

In [127]:
# Set up the ANN
# Sequential layer - ANN is a sequence of layers, other type is computational graph

# TensorFlow and Keras are combined together.

# Make an instance, object, sequential
ann = tf.keras.models.Sequential()

In [128]:
# Add the input layer, and add the hidden layer
# Use the Dense class

# How to add fully connected:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

# Several arguments:
# units = number of neurons in want in that specific layer.
# First Hidden Layer = 6 neurons

# do not confuse independent variables 
# How do you know how many hidden layers to have - no, you need to experiment with hyperparameters
# The instructor tried several numbers, it ended up being 6.
# Activation = Rectifier Function is the most popular one.

In [129]:
# Add the second hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

In [130]:
# Add the output layer
# Units = 1, since we are doing binary categorical variable.
# If it's categorical, it'd be unit = 3

# This depends on the nature of your final
ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# soft max -> if not binary, like categorical var predictions, change activation to soft max

# Why Sigmoid? It gets you the prediction, and the prediction that the binary outcome is 1.
# You get the probability number.

# Part 3: Train the ANN

In [131]:
# Compile the ANN
ann.compile(optimizer= "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

# Parameters;
# Metrics - classification, let's usee accuracy. You can pick accuracy, precision and recall, or f1-score.
# optimizer - best to use is SDG - "adam", it does SDG, which is the best for ANN
# Loss function (Cost) - when doing binary classification, the loss function must be binary_crossentropy

# If not binary, like categorical variable => category_crossentropy

In [132]:
# Train the ANN on training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

# Parameters:
# batch_size = batch learning is more better for performance efficiency
# epochs = certain number of epochs, we will use 100

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 263us/step - accuracy: 0.5336 - loss: 0.6948
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 233us/step - accuracy: 0.8010 - loss: 0.4905
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 233us/step - accuracy: 0.8028 - loss: 0.4518
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 239us/step - accuracy: 0.8142 - loss: 0.4342
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 240us/step - accuracy: 0.8175 - loss: 0.4333
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 238us/step - accuracy: 0.8252 - loss: 0.4159
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 228us/step - accuracy: 0.8263 - loss: 0.4122
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 232us/step - accuracy: 0.8201 - loss: 0.4227
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 230us/step - accuracy: 0.8309 - loss: 0.4029
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 261us/step - accuracy: 0.8342 - loss: 0.4003
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - accuracy: 0.8352 - loss: 0.3932
Epoch 12/100
250/25

In [133]:
# Object is ann
X_test[0]

array([-0.99850112,  1.72572313, -0.57638802, -0.57749609,  0.91324755,
       -0.6557859 , -0.69539349,  0.32993735,  0.80843615, -1.54035103,
       -1.02583358, -1.01960511])

# Part 4 - Use ANN for prediction

In [134]:
# Task:
# French Customer
# Credit Score = 600
# Gender = Male
# Age: 40 years old
# Tenure: 3 years
# Balance: 60,000
# Number of Products: 2
# Credit Card = Yes
# Active member = yes
# Estimated Salary = 50,000

# Is this customer expected to leave our bank? Churn Y/N?

In [135]:
X_test[0]

array([-0.99850112,  1.72572313, -0.57638802, -0.57749609,  0.91324755,
       -0.6557859 , -0.69539349,  0.32993735,  0.80843615, -1.54035103,
       -1.02583358, -1.01960511])

In [136]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [157]:
# Prediction set.
# We only need scaling, so only call transform()

# Sigmoid function -> result is 0 or 1. Therefore, probability is 0 or 1.
# We need to set a threshold
prob_result = ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

# Unpacking two levels down - use math logic - removal of 2 levels of nesting in LS = does the same for RS
[[result]] = prob_result

print(f"The probability this customer will leave is {result*100:3f}%!")

# Our threshold for binary classification is 0.5 Thus, if the number is higher than 0.5, we can assume they will leave.
result > 0.5 # Not leaving

# [1,0,0] = France
# Be super careful of how things are encoded.
# We predict this customer will not leave, yay!

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
The probability this customer will leave is 2.837898%!


False

In [162]:
# Next task:

# Pass the results in x_test
predictions = ann.predict(X_test)

# Compare the results. Convert the probabilities to Class:
y_pred = predictions > 0.5

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 202us/step


In [163]:
type(y_pred)

numpy.ndarray

In [165]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


In [166]:
# Create the confusion matrix
# You need to y_pred and y_test, make sure they are in the same shape

from sklearn.metrics import confusion_matrix, accuracy_score

In [169]:
# Results are Class 0,1
y_test

array([0, 0, 0, ..., 1, 1, 1])

In [171]:
# Confusion Matrix. Remember Actuals are always on the top, the side is always prediction.
confusion_matrix(y_test, y_pred)

print(confusion_matrix(y_test, y_pred))

# 0,0 => 1540 - 0,1 = FN 67 - 1,0 (actually stayed but misclassified), 185 (FP) - missed by mistake, actually left but missclassifie

# Pretty good!
accuracy_score(y_test, y_pred)

[[1540   67]
 [ 208  185]]


0.8625

# Machine Learning Process:

1. Data Pre-Processing
* Loading data
* Add the import packages
* Data cleaning and validating
* Missing data
* EDA

2. Model Building and Training
* Feature engineering
* Feature scaling - important for models who are sensitive to different ranges and outliers
* Pick Models, apply the models
* Hyper-parameter tuning


3. Evaluation - performance metrics and Make a verdict
* Metrics - MAE/MSE/RMSE + CROSS-VAL + ACCURACY/PRECISION/RECALL/F1-SCORE
* Recommend a model and make feature importance implications